version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: margumedo 
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nestdb 
    ports:
      - "5499:5432"